### ISSUE TITLE
0.9 fails to connect (timeout), 0.8 works fine

### ISSUE THREAD

**Issue by yatesco** [prisma/tiberius#220]
Hiya, I haven't debugged this yet, but I wanted to report it ASAP. Upgrading from 0.8 to 0.9 results in every connection failing and timing out.

`Cargo.toml`:
```toml
# MSSQL
futures = "0.3"
futures-util = "0.3"
# 0.9 times out (no idea why!) so lock to 0.8
tiberius = { version = "0.8", features = ["chrono", "tokio"] }
bb8-tiberius = "0.11"
```

My code:
```rust
        use config::DatabaseURLConstructor;
        use tiberius::Client;
        use tokio::net::TcpStream;
        use tokio_util::compat::TokioAsyncWriteCompatExt;

        let db_config = config::parse().unwrap().pride_and_joy_db;
        let config = tiberius::Config::from_ado_string(&db_config.construct())?;

        let tcp = TcpStream::connect(config.get_addr()).await?;
        tcp.set_nodelay(true)?;

        let out conn = Client::connect(config, tcp.compat_write()).await?;

        println!("Connected"); // - NEVER GETS HERE      
```

My connection string: `server=tcp:127.0.0.1,1433;encrypt=false;TrustServerCertificate=true;user=XXX;password=YYY;database=AAAA;`

Any pointers? Thanks!
