### ISSUE TITLE
Add docs for feature native-tls and rustls

### ISSUE THREAD

**Issue by kzhui125** [prisma/tiberius#363]
for my testing:

macOS 15 + native-tls: connection timeout error to sql server 2019/2022
macOS 15 + rustls: connection ok to sql server 2019/2022
Windows + native-tls: connection ok to sql server 2014/2019/2022
Windows + rustls: connection ok to sql server 2019/2022, connection timeout to sql server 2014 in Windows Server 2012R2

It's better to add docs for native-tls and rustls

I recommend using config like this:

```toml
[target.'cfg(windows)'.dependencies.tiberius]
version = "0.12"
default-features = false
features = ["native-tls", "tds73", "winauth", "chrono", "rust_decimal"]

[target.'cfg(not(windows))'.dependencies.tiberius]
version = "0.12"
default-features = false
features = ["rustls", "tds73", "winauth", "chrono", "rust_decimal"]
```

I have not tested for Linux yet.
